name: dart-async
version: 0.0.0
author: Radek <dev@radekstepan.com>
description: Async operations ala caolan/async.
homepage: https://github.com/radekstepan/dart-async
environment:
    sdk: ">=1.0.0"
dev_dependencies:
    unittest: "0.9.0"